image: golang:1.13.4-alpine3.10

stages:
  - build
  - test

build:
  stage: build
  script:
    - go mod download
    - go build ./...
  only:
    changes:
      - go*
      - "*.go"
      - ".gitlab-ci.yml"
  tags:
    - build

test:
  stage: test
  variables:
    CGO_ENABLED: "0"
  script:
    - go mod download
    - go test -v ./...
  only:
    changes:
      - go*
      - "*.go"
      - ".gitlab-ci.yml"
  tags:
    - build
