image: golang:1.13.4-alpine3.10

stages:
  - build
  - test

build:
  stage: build
  script:
    - go mod download
    - go build ./logger
  only:
    changes:
      - go*
      - logger/**/*
      - ".gitlab-ci.yml"
  tags:
    - build

test:
  stage: test
  script:
    - go mod download
    - go test ./...
  only:
    changes:
      - go*
      - logger/**/*
      - ".gitlab-ci.yml"
  tags:
    - build
